_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.0
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
agent:
    value: a_star
depth_limit:
    value: 0
num_games:
    value: 10
