_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.0
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
agent:
    value: td_learning
discount_factor:
    value: 6
epsilon:
    value: 0.1
learning_rate:
    value: 0.01
num_games:
    value: 50
